export const ONE_SECOND = 1000
export const ONE_MINUTE = ONE_SECOND * 60
export const ONE_HOUR = ONE_MINUTE * 60
export const ONE_DAY = ONE_HOUR * 24

export const JWT_EXPIRATION_TIME = '24h'
export const WHATSAPP_VERIFICATION_TTL_SECONDS = 600
export const WHATSAPP_VERIFICATION_TTL_MS = WHATSAPP_VERIFICATION_TTL_SECONDS * ONE_SECOND
