// To-Do: Remove unecessary icons

import {
  AirplaneIcon,
  ArrowsMergeIcon,
  BabyIcon,
  BeerBottleIcon,
  BeerSteinIcon,
  BookIcon,
  BowlFoodIcon,
  BreadIcon,
  CakeIcon,
  CalendarIcon,
  CheckIcon,
  ChefHatIcon,
  CircleIcon,
  ClockIcon,
  CloudIcon,
  CoffeeIcon,
  CoinsIcon,
  CookieIcon,
  CowIcon,
  CrownIcon,
  DropIcon,
  FeatherIcon,
  FireIcon,
  FishIcon,
  FlagIcon,
  FlameIcon,
  FlaskIcon,
  ForkKnifeIcon,
  GrainsIcon,
  HamburgerIcon,
  HammerIcon,
  HandIcon,
  HeartIcon,
  HouseIcon,
  IceCreamIcon,
  KnifeIcon,
  LeafIcon,
  LightningIcon,
  MapPinIcon,
  MartiniIcon,
  MoonIcon,
  OvenIcon,
  PackageIcon,
  PaletteIcon,
  PiggyBankIcon,
  PizzaIcon,
  ShieldIcon,
  SignatureIcon,
  SnowflakeIcon,
  SparkleIcon,
  StarIcon,
  SunIcon,
  ThumbsUpIcon,
  TreeIcon,
  TrendDownIcon,
  TrendUpIcon,
  TrophyIcon,
  TruckIcon,
  UsersIcon,
  WarningIcon,
  WineIcon,
  XIcon
} from '@phosphor-icons/react'

export const ICONS_KEYS: Record<string, string> = {
  food: 'Hamburger',
  pizza: 'Pizza',
  pasta: 'BowlFood',
  steak: 'Knife',
  fish: 'Fish',
  beef: 'Cow',
  pork: 'PiggyBank',
  drink: 'Coffee',
  beer: 'BeerStein',
  wine: 'Wine',
  cocktail: 'Martini',
  juice: 'Drop',
  soda: 'BeerBottle',
  water: 'Drop',
  tea: 'Coffee',
  dessert: 'Cake',
  ice_cream: 'IceCream',
  cake: 'Cake',
  cookie: 'Cookie',
  side: 'ForkKnife',
  salad: 'Leaf',
  rice: 'Grains',
  bread: 'Bread',
  grilled: 'Flame',
  fried: 'Fire',
  baked: 'Oven',
  steamed: 'Cloud',
  raw: 'Leaf',
  spicy: 'Flame',
  vegetarian: 'Leaf',
  vegan: 'Leaf',
  gluten_free: 'Shield',
  organic: 'Leaf',
  fresh: 'Leaf',
  hot: 'Flame',
  cold: 'Snowflake',
  breakfast: 'Sun',
  lunch: 'Sun',
  dinner: 'Moon',
  snack: 'Clock',
  special: 'Star',
  popular: 'TrendUp',
  new: 'Sparkle',
  chef: 'ChefHat',
  premium: 'Crown',
  kids: 'Baby',
  fork_knife: 'ForkKnife',
  plate: 'Circle',
  bowl: 'BowlFood',
  cup: 'Circle',
  glass: 'Circle',
  cheese: 'Circle',
  tomato: 'Circle',
  onion: 'Circle',
  garlic: 'Circle',
  pepper: 'Circle',
  salt: 'Circle',
  oil: 'Drop',
  butter: 'Circle',
  appetizer: 'Circle',
  soup: 'BowlFood',
  sandwich: 'Hamburger',
  burger: 'Hamburger',
  hot_dog: 'Hamburger',
  taco: 'Circle',
  sushi: 'Circle',
  ramen: 'BowlFood',
  curry: 'BowlFood',
  espresso: 'Coffee',
  cappuccino: 'Coffee',
  latte: 'Coffee',
  mocha: 'Coffee',
  hot_chocolate: 'Coffee',
  milkshake: 'Drop',
  smoothie: 'Drop',
  lemonade: 'Drop',
  iced_tea: 'Coffee',
  chocolate: 'Circle',
  vanilla: 'Circle',
  strawberry: 'Circle',
  caramel: 'Circle',
  nuts: 'Circle',
  available: 'Check',
  unavailable: 'X',
  limited: 'Warning',
  sold_out: 'X',
  cheap: 'Coins',
  affordable: 'Coins',
  expensive: 'Crown',
  luxury: 'Crown',
  small: 'Circle',
  medium: 'Circle',
  large: 'Circle',
  family: 'Users',
  fast: 'Lightning',
  slow: 'Clock',
  quick: 'Lightning',
  healthy: 'Heart',
  light: 'Feather',
  low_calorie: 'TrendDown',
  protein: 'Circle',
  fiber: 'Circle',
  seasonal: 'Calendar',
  summer: 'Sun',
  winter: 'Snowflake',
  spring: 'Leaf',
  autumn: 'Leaf',
  birthday: 'Cake',
  anniversary: 'Heart',
  local: 'MapPin',
  imported: 'Airplane',
  regional: 'MapPin',
  traditional: 'Book',
  handmade: 'Hand',
  artisanal: 'Palette',
  homemade: 'House',
  craft: 'Hammer',
  delivery: 'Truck',
  takeaway: 'Package',
  dine_in: 'House',
  outdoor: 'Tree',
  favorite: 'Heart',
  recommended: 'ThumbsUp',
  award: 'Trophy',
  certified: 'Shield',
  quality: 'Star',
  authentic: 'Shield',
  original: 'Star',
  classic: 'Book',
  modern: 'Lightning',
  fusion: 'ArrowsMerge',
  experimental: 'Flask',
  signature: 'Signature',
  house: 'House',
  daily: 'Calendar',
  weekly: 'Calendar',
  monthly: 'Calendar'
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ICONS: Record<keyof typeof ICONS_KEYS, React.ComponentType<any>> = {
  Hamburger: HamburgerIcon,
  Pizza: PizzaIcon,
  BowlFood: BowlFoodIcon,
  Knife: KnifeIcon,
  Fish: FishIcon,
  Cow: CowIcon,
  PiggyBank: PiggyBankIcon,
  Coffee: CoffeeIcon,
  BeerStein: BeerSteinIcon,
  Wine: WineIcon,
  Martini: MartiniIcon,
  Drop: DropIcon,
  BeerBottle: BeerBottleIcon,
  Cake: CakeIcon,
  IceCream: IceCreamIcon,
  Cookie: CookieIcon,
  ForkKnife: ForkKnifeIcon,
  Leaf: LeafIcon,
  Grains: GrainsIcon,
  Bread: BreadIcon,
  Flag: FlagIcon,
  Flame: FlameIcon,
  Fire: FireIcon,
  Oven: OvenIcon,
  Cloud: CloudIcon,
  Shield: ShieldIcon,
  Snowflake: SnowflakeIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Clock: ClockIcon,
  Star: StarIcon,
  TrendUp: TrendUpIcon,
  Sparkle: SparkleIcon,
  ChefHat: ChefHatIcon,
  Crown: CrownIcon,
  Baby: BabyIcon,
  Circle: CircleIcon,
  Check: CheckIcon,
  X: XIcon,
  Warning: WarningIcon,
  Coins: CoinsIcon,
  Users: UsersIcon,
  Lightning: LightningIcon,
  Heart: HeartIcon,
  Feather: FeatherIcon,
  TrendDown: TrendDownIcon,
  Calendar: CalendarIcon,
  MapPin: MapPinIcon,
  Airplane: AirplaneIcon,
  Book: BookIcon,
  Hand: HandIcon,
  Palette: PaletteIcon,
  House: HouseIcon,
  Hammer: HammerIcon,
  Truck: TruckIcon,
  Package: PackageIcon,
  Tree: TreeIcon,
  ThumbsUp: ThumbsUpIcon,
  Trophy: TrophyIcon,
  ArrowsMerge: ArrowsMergeIcon,
  Flask: FlaskIcon,
  Signature: SignatureIcon
}
