import {
  BeerBottleIcon,
  BeerSteinIcon,
  BowlFoodIcon,
  BreadIcon,
  CakeIcon,
  CloudIcon,
  CoffeeIcon,
  CookieIcon,
  DropIcon,
  FireIcon,
  FishIcon,
  FlameIcon,
  ForkKnifeIcon,
  GrainsIcon,
  HamburgerIcon,
  IceCreamIcon,
  KnifeIcon,
  LeafIcon,
  MartiniIcon,
  OvenIcon,
  PizzaIcon,
  ShieldIcon,
  WineIcon
} from '@phosphor-icons/react'

export const ICONS_KEYS: Record<string, string> = {
  burger: 'Hamburger',
  pizza: 'Pizza',
  pasta: 'BowlFood',
  steak: 'Knife',
  fish: 'Fish',
  coffee: 'Coffee',
  beer: 'BeerStein',
  wine: 'Wine',
  cocktail: 'Martini',
  juice: 'Drop',
  soda: 'BeerBottle',
  dessert: 'Cake',
  ice_cream: 'IceCream',
  cookie: 'Cookie',
  side: 'ForkKnife',
  salad: 'Leaf',
  rice: 'Grains',
  bread: 'Bread',
  grilled: 'Flame',
  fried: 'Fire',
  baked: 'Oven',
  steamed: 'Cloud',
  gluten_free: 'Shield'
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ICONS: Record<keyof typeof ICONS_KEYS, React.ComponentType<any>> = {
  Hamburger: HamburgerIcon,
  Pizza: PizzaIcon,
  BowlFood: BowlFoodIcon,
  Knife: KnifeIcon,
  Fish: FishIcon,
  Coffee: CoffeeIcon,
  BeerStein: BeerSteinIcon,
  Wine: WineIcon,
  Martini: MartiniIcon,
  Drop: DropIcon,
  BeerBottle: BeerBottleIcon,
  Cake: CakeIcon,
  IceCream: IceCreamIcon,
  Cookie: CookieIcon,
  ForkKnife: ForkKnifeIcon,
  Leaf: LeafIcon,
  Grains: GrainsIcon,
  Bread: BreadIcon,
  Flame: FlameIcon,
  Fire: FireIcon,
  Oven: OvenIcon,
  Cloud: CloudIcon,
  Shield: ShieldIcon
}
